### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by fredyshox** [Holdapp/locgen-swift#14]
It would be really cool, if we could install this via Homebrew (maybe custom tap for hldp tools)?

**Comment by lukasz-szyszkowski** [comment]
That's a great idea!

**Comment by lukasz-szyszkowski** [comment]
related to PR #16

**Comment by fredyshox** [comment]
locgen-swift formulae has just been added to [holdapp/tap-public](https://github.com/Holdapp/homebrew-tap-public).
